"""Skill extractor service.

Consolidates raw data from GitHub, CV, and portfolio sources into a single
deduplicated skill list with occurrence counts and source attribution.
"""

from __future__ import annotations

from typing import Any


def _normalize_name(name: str) -> str:
    """Lower-case and strip whitespace for dedup comparisons."""
    return name.strip().lower()


# Canonical display names for common aliases
_ALIASES: dict[str, str] = {
    # Languages
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "py": "Python",
    "python": "Python",
    "java": "Java",
    "c#": "C#",
    "csharp": "C#",
    "c++": "C++",
    "cpp": "C++",
    "go": "Go",
    "golang": "Go",
    "rb": "Ruby",
    "ruby": "Ruby",
    "php": "PHP",
    "rust": "Rust",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "html": "HTML",
    "css": "CSS",
    "sass": "Sass",
    "less": "LESS",
    "r": "R",
    "rlang": "R",
    "matlab": "MATLAB",
    "julia": "Julia",
    "perl": "Perl",
    "lua": "Lua",
    "haskell": "Haskell",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "clojure": "Clojure",
    "f#": "F#",
    "fsharp": "F#",
    "ocaml": "OCaml",
    "dart": "Dart",
    "zig": "Zig",
    "nim": "Nim",
    "groovy": "Groovy",
    "vba": "VBA",
    "shell": "Shell",
    "bash": "Bash",
    "powershell": "PowerShell",
    "ps": "PowerShell",
    "sql": "SQL",
    "plsql": "PL/SQL",
    "tsql": "T-SQL",
    "cobol": "COBOL",
    "fortran": "Fortran",
    "assembly": "Assembly",
    "asm": "Assembly",
    "solidity": "Solidity",
    "move": "Move",
    "vyper": "Vyper",
    "abap": "ABAP",
    "apex": "Apex",
    "obj-c": "Objective-C",
    "objc": "Objective-C",
    "objective-c": "Objective-C",

    # Frontend Frameworks & Libraries
    "react": "React",
    "reactjs": "React",
    "angular": "Angular",
    "vue": "Vue",
    "vuejs": "Vue",
    "svelte": "Svelte",
    "sveltekit": "SvelteKit",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "nuxt": "Nuxt",
    "nuxtjs": "Nuxt",
    "gatsby": "Gatsby",
    "remix": "Remix",
    "astro": "Astro",
    "solidjs": "SolidJS",
    "qwik": "Qwik",
    "ember": "Ember.js",
    "emberjs": "Ember.js",
    "backbone": "Backbone.js",
    "backbonejs": "Backbone.js",
    "jquery": "jQuery",
    "htmx": "HTMX",
    "alpinejs": "Alpine.js",
    "alpine": "Alpine.js",
    "preact": "Preact",
    "lit": "Lit",
    "stencil": "Stencil",
    "web components": "Web Components",

    # CSS Frameworks & Tools
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "mui": "Material UI",
    "chakra": "Chakra UI",
    "chakra ui": "Chakra UI",
    "shadcn": "shadcn/ui",
    "shadcn/ui": "shadcn/ui",
    "ant design": "Ant Design",
    "antd": "Ant Design",
    "styled components": "Styled Components",
    "emotion": "Emotion",
    "bulma": "Bulma",
    "foundation": "Foundation",
    "daisyui": "DaisyUI",
    "mantine": "Mantine",
    "radix": "Radix UI",
    "radix ui": "Radix UI",
    "framer motion": "Framer Motion",
    "gsap": "GSAP",
    "three.js": "Three.js",
    "threejs": "Three.js",
    "d3": "D3.js",
    "d3.js": "D3.js",

    # Backend Frameworks
    "spring boot": "Spring Boot",
    "spring": "Spring Boot",
    "springboot": "Spring Boot",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "express": "Express",
    "expressjs": "Express",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "node": "Node.js",
    "rails": "Rails",
    "ruby on rails": "Rails",
    "laravel": "Laravel",
    ".net": ".NET",
    "dotnet": ".NET",
    "asp.net": "ASP.NET",
    "blazor": "Blazor",
    "actix": "Actix",
    "axum": "Axum",
    "rocket": "Rocket",
    "gin": "Gin",
    "fiber": "Fiber",
    "echo": "Echo",
    "fastify": "Fastify",
    "nestjs": "NestJS",
    "nest": "NestJS",
    "hapi": "Hapi.js",
    "koa": "Koa",
    "koajs": "Koa",
    "phoenix": "Phoenix",
    "ktor": "Ktor",
    "quarkus": "Quarkus",
    "micronaut": "Micronaut",
    "play": "Play Framework",
    "play framework": "Play Framework",
    "symfony": "Symfony",
    "codeigniter": "CodeIgniter",
    "yii": "Yii",
    "cakephp": "CakePHP",
    "strapi": "Strapi",
    "directus": "Directus",
    "payload": "Payload CMS",
    "payload cms": "Payload CMS",

    # Mobile
    "flutter": "Flutter",
    "react native": "React Native",
    "rn": "React Native",
    "expo": "Expo",
    "ionic": "Ionic",
    "capacitor": "Capacitor",
    "cordova": "Cordova",
    "xamarin": "Xamarin",
    "maui": ".NET MAUI",
    ".net maui": ".NET MAUI",
    "swiftui": "SwiftUI",
    "uikit": "UIKit",
    "jetpack compose": "Jetpack Compose",
    "compose": "Jetpack Compose",

    # Cloud & DevOps
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "google cloud": "GCP",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "ci/cd": "CI/CD",
    "devops": "DevOps",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "circleci": "CircleCI",
    "travis ci": "Travis CI",
    "argocd": "ArgoCD",
    "argo": "ArgoCD",
    "helm": "Helm",
    "istio": "Istio",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "datadog": "Datadog",
    "splunk": "Splunk",
    "elk": "ELK Stack",
    "pulumi": "Pulumi",
    "serverless": "Serverless",
    "cloudformation": "CloudFormation",
    "cdk": "AWS CDK",
    "aws cdk": "AWS CDK",
    "vagrant": "Vagrant",
    "packer": "Packer",
    "vault": "HashiCorp Vault",
    "consul": "Consul",
    "nomad": "Nomad",
    "podman": "Podman",
    "openshift": "OpenShift",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "heroku": "Heroku",
    "render": "Render",
    "fly.io": "Fly.io",
    "cloudflare": "Cloudflare",

    # Databases
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "sqlite": "SQLite",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "firestore": "Firestore",
    "firebase": "Firebase",
    "supabase": "Supabase",
    "cockroachdb": "CockroachDB",
    "cockroach": "CockroachDB",
    "neo4j": "Neo4j",
    "influxdb": "InfluxDB",
    "timescaledb": "TimescaleDB",
    "clickhouse": "ClickHouse",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Redshift",
    "mariadb": "MariaDB",
    "oracle": "Oracle DB",
    "oracle db": "Oracle DB",
    "ms sql": "SQL Server",
    "mssql": "SQL Server",
    "sql server": "SQL Server",
    "couchdb": "CouchDB",
    "couchbase": "Couchbase",
    "fauna": "FaunaDB",
    "faunadb": "FaunaDB",
    "planetscale": "PlanetScale",
    "neon": "Neon",
    "turso": "Turso",
    "drizzle": "Drizzle ORM",
    "drizzle orm": "Drizzle ORM",
    "prisma": "Prisma",
    "typeorm": "TypeORM",
    "sequelize": "Sequelize",
    "sqlalchemy": "SQLAlchemy",
    "hibernate": "Hibernate",

    # APIs & Protocols
    "graphql": "GraphQL",
    "rest": "REST",
    "grpc": "gRPC",
    "websockets": "WebSockets",
    "websocket": "WebSockets",
    "mqtt": "MQTT",
    "openapi": "OpenAPI",
    "swagger": "Swagger",
    "trpc": "tRPC",
    "json:api": "JSON:API",
    "jsonapi": "JSON:API",
    "oauth": "OAuth",
    "oauth2": "OAuth 2.0",
    "jwt": "JWT",
    "saml": "SAML",
    "oidc": "OpenID Connect",
    "openid": "OpenID Connect",

    # Messaging & Streaming
    "kafka": "Kafka",
    "rabbitmq": "RabbitMQ",
    "nats": "NATS",
    "sqs": "Amazon SQS",
    "pub/sub": "Google Pub/Sub",
    "pubsub": "Google Pub/Sub",
    "celery": "Celery",
    "redis streams": "Redis Streams",
    "activemq": "ActiveMQ",
    "pulsar": "Apache Pulsar",
    "kinesis": "Amazon Kinesis",

    # AI & ML
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "nlp": "NLP",
    "natural language processing": "NLP",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "llm": "LLMs",
    "llms": "LLMs",
    "generative ai": "Generative AI",
    "gen ai": "Generative AI",
    "rag": "RAG",
    "langchain": "LangChain",
    "langgraph": "LangGraph",
    "llamaindex": "LlamaIndex",
    "llama index": "LlamaIndex",
    "hugging face": "Hugging Face",
    "huggingface": "Hugging Face",
    "openai": "OpenAI API",
    "openai api": "OpenAI API",
    "anthropic": "Anthropic API",
    "anthropic api": "Anthropic API",
    "stable diffusion": "Stable Diffusion",
    "diffusers": "Diffusers",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "keras": "Keras",
    "jax": "JAX",
    "opencv": "OpenCV",
    "spacy": "spaCy",
    "nltk": "NLTK",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "scipy": "SciPy",
    "mlflow": "MLflow",
    "dvc": "DVC",
    "weights & biases": "Weights & Biases",
    "wandb": "Weights & Biases",
    "ray": "Ray",
    "dask": "Dask",
    "spark": "Apache Spark",
    "pyspark": "PySpark",
    "airflow": "Apache Airflow",
    "prefect": "Prefect",
    "dagster": "Dagster",
    "feast": "Feast",
    "triton": "Triton",
    "onnx": "ONNX",
    "vllm": "vLLM",
    "llamacpp": "llama.cpp",
    "llama.cpp": "llama.cpp",
    "ollama": "Ollama",
    "crew ai": "CrewAI",
    "crewai": "CrewAI",
    "autogen": "AutoGen",
    "semantic kernel": "Semantic Kernel",
    "vector db": "Vector Databases",
    "pinecone": "Pinecone",
    "weaviate": "Weaviate",
    "qdrant": "Qdrant",
    "chroma": "ChromaDB",
    "chromadb": "ChromaDB",
    "milvus": "Milvus",

    # Testing
    "jest": "Jest",
    "vitest": "Vitest",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "selenium": "Selenium",
    "pytest": "Pytest",
    "unittest": "unittest",
    "mocha": "Mocha",
    "chai": "Chai",
    "jasmine": "Jasmine",
    "junit": "JUnit",
    "testng": "TestNG",
    "rspec": "RSpec",
    "storybook": "Storybook",
    "testing library": "Testing Library",

    # Build Tools & Bundlers
    "webpack": "Webpack",
    "vite": "Vite",
    "rollup": "Rollup",
    "esbuild": "esbuild",
    "parcel": "Parcel",
    "turbopack": "Turbopack",
    "turborepo": "Turborepo",
    "nx": "Nx",
    "bazel": "Bazel",
    "gradle": "Gradle",
    "maven": "Maven",
    "cargo": "Cargo",
    "pip": "pip",
    "poetry": "Poetry",
    "uv": "uv",
    "bun": "Bun",
    "deno": "Deno",
    "pnpm": "pnpm",
    "yarn": "Yarn",
    "npm": "npm",
    "cmake": "CMake",
    "make": "Make",

    # Version Control & Collaboration
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "svn": "SVN",
    "mercurial": "Mercurial",

    # Architecture & Patterns
    "microservices": "Microservices",
    "monorepo": "Monorepo",
    "event driven": "Event-Driven Architecture",
    "event-driven": "Event-Driven Architecture",
    "ddd": "Domain-Driven Design",
    "domain driven design": "Domain-Driven Design",
    "cqrs": "CQRS",
    "tdd": "TDD",
    "bdd": "BDD",
    "solid": "SOLID Principles",
    "clean architecture": "Clean Architecture",
    "hexagonal": "Hexagonal Architecture",
    "api gateway": "API Gateway",
    "service mesh": "Service Mesh",
    "web3": "Web3",
    "blockchain": "Blockchain",

    # OS & Systems
    "linux": "Linux",
    "ubuntu": "Ubuntu",
    "debian": "Debian",
    "fedora": "Fedora",
    "centos": "CentOS",
    "rhel": "RHEL",
    "arch linux": "Arch Linux",
    "macos": "macOS",
    "windows server": "Windows Server",
    "nginx": "Nginx",
    "apache": "Apache",
    "caddy": "Caddy",
    "haproxy": "HAProxy",

    # Methodology
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "lean": "Lean",
    "xp": "Extreme Programming",
    "extreme programming": "Extreme Programming",
    "pair programming": "Pair Programming",
    "code review": "Code Review",

    # Security
    "owasp": "OWASP",
    "penetration testing": "Penetration Testing",
    "pen testing": "Penetration Testing",
    "soc 2": "SOC 2",
    "soc2": "SOC 2",
    "zero trust": "Zero Trust",
    "devsecops": "DevSecOps",

    # Design & Product
    "figma": "Figma",

    "confluence": "Confluence",
    "notion": "Notion",
    "linear": "Linear",
    "asana": "Asana",
    "trello": "Trello",
    "miro": "Miro",
    "sketch": "Sketch",
    "adobe xd": "Adobe XD",
    "zeplin": "Zeplin",
    "storyblok": "Storyblok",
    "contentful": "Contentful",
    "sanity": "Sanity",
    "wordpress": "WordPress",
    "wp": "WordPress",
    "shopify": "Shopify",
    "webflow": "Webflow",

    # Analytics & Monitoring
    "google analytics": "Google Analytics",
    "ga4": "Google Analytics 4",
    "segment": "Segment",
    "mixpanel": "Mixpanel",
    "amplitude": "Amplitude",
    "posthog": "PostHog",
    "sentry": "Sentry",
    "new relic": "New Relic",
    "pagerduty": "PagerDuty",
    "opentelemetry": "OpenTelemetry",
    "otel": "OpenTelemetry",

    # Blockchain & Web3
    "ethereum": "Ethereum",
    "eth": "Ethereum",
    "solana": "Solana",
    "sol": "Solana",
    "hardhat": "Hardhat",
    "foundry": "Foundry",
    "ethers.js": "Ethers.js",
    "ethersjs": "Ethers.js",
    "web3.js": "Web3.js",
    "web3js": "Web3.js",
    "ipfs": "IPFS",
}


def _canonicalize(name: str) -> str:
    key = _normalize_name(name)
    return _ALIASES.get(key, name.strip())


def extract_skills(
    github_data: dict[str, Any],
    cv_data: dict[str, Any],
    portfolio_data: dict[str, Any],
) -> list[dict[str, Any]]:
    """Merge skills from all sources into a unified list.

    Returns a list of dicts with keys: name, sources, occurrence_count.
    """
    skill_map: dict[str, dict[str, Any]] = {}

    def _add(name: str, source: str) -> None:
        canonical = _canonicalize(name)
        key = _normalize_name(canonical)
        if key not in skill_map:
            skill_map[key] = {"name": canonical, "sources": set(), "occurrence_count": 0}
        skill_map[key]["sources"].add(source)
        skill_map[key]["occurrence_count"] += 1

    # GitHub: languages + detected frameworks
    if github_data and not github_data.get("error"):
        for lang in github_data.get("language_stats", {}):
            _add(lang, "github")
        for fw in github_data.get("detected_frameworks", []):
            _add(fw, "github")

    # CV: technologies
    if cv_data and not cv_data.get("error"):
        for tech in cv_data.get("technologies", []):
            _add(tech, "cv")

    # Portfolio: technologies
    if portfolio_data and not portfolio_data.get("error"):
        for tech in portfolio_data.get("technologies", []):
            _add(tech, "portfolio")

    # Convert sets to lists for JSON serialization
    results = []
    for item in skill_map.values():
        results.append(
            {
                "name": item["name"],
                "sources": sorted(item["sources"]),
                "occurrence_count": item["occurrence_count"],
            }
        )

    # Sort by occurrence count descending, then alphabetically
    results.sort(key=lambda s: (-s["occurrence_count"], s["name"]))
    return results
